-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.25-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table irena3.irena_usulan_pln
DROP TABLE IF EXISTS `irena_usulan_pln`;
CREATE TABLE IF NOT EXISTS `irena_usulan_pln` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_instansi` varchar(11) NOT NULL,
  `id_eselon_1` varchar(11) NOT NULL,
  `instansi_pelaksana` text NOT NULL,
  `id_program` varchar(11) NOT NULL,
  `proyeksi_tahun_pertama_penarikan` int(11) NOT NULL,
  `judul_proyek_id` varchar(300) NOT NULL,
  `judul_proyek_eng` varchar(300) NOT NULL,
  `ruang_lingkup_id` text NOT NULL,
  `ruang_lingkup_eng` text NOT NULL,
  `dana_usulan` bigint(20) NOT NULL,
  `dana_hibah` bigint(20) NOT NULL,
  `tahun_usulan` bigint(20) NOT NULL,
  `durasi` int(11) NOT NULL,
  `output` text NOT NULL,
  `outcome` text NOT NULL,
  `dana_pendamping` int(11) NOT NULL,
  `is_BB` int(11) NOT NULL DEFAULT '0',
  `is_GB` int(11) NOT NULL DEFAULT '0',
  `is_DK` int(11) NOT NULL DEFAULT '0',
  `is_LA` int(11) NOT NULL DEFAULT '0',
  `Files` varchar(500) NOT NULL,
  `lokasi` varchar(200) NOT NULL,
  `id_sektor` int(11) NOT NULL,
  `infra` int(11) NOT NULL,
  `id_status` int(11) NOT NULL DEFAULT '1',
  `status_usulan` int(11) NOT NULL DEFAULT '0',
  `id_usulan_hub` varchar(50) NOT NULL,
  `id_provinsi` varchar(50) DEFAULT NULL,
  `id_kabkota` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=latin1;

-- Dumping data for table irena3.irena_usulan_pln: ~6 rows (approximately)
DELETE FROM `irena_usulan_pln`;
/*!40000 ALTER TABLE `irena_usulan_pln` DISABLE KEYS */;
INSERT INTO `irena_usulan_pln` (`id`, `id_instansi`, `id_eselon_1`, `instansi_pelaksana`, `id_program`, `proyeksi_tahun_pertama_penarikan`, `judul_proyek_id`, `judul_proyek_eng`, `ruang_lingkup_id`, `ruang_lingkup_eng`, `dana_usulan`, `dana_hibah`, `tahun_usulan`, `durasi`, `output`, `outcome`, `dana_pendamping`, `is_BB`, `is_GB`, `is_DK`, `is_LA`, `Files`, `lokasi`, `id_sektor`, `infra`, `id_status`, `status_usulan`, `id_usulan_hub`, `id_provinsi`, `id_kabkota`) VALUES
	(26, '15', '', 'Kementerian Perhubungan', '7', 2018, 'Pembangunan Pelabuhan Patimban Subang Jawa Barat', 'The Development of Patimban Port-Stage 1', 'a. Penyusunan desain serta spesifikasi teknis;\r\nb. Pelaksanaan pelelangan;\r\nc. Pelaksanaan kegiatan konstruksi;\r\nd. Pelaksanaan serah terima hasil pekerjaan;\r\ne. Konsesi dan kerjasama pengoperasian pelabuhan.', 'a. Penyusunan desain serta spesifikasi teknis;\r\nb. Pelaksanaan pelelangan;\r\nc. Pelaksanaan kegiatan konstruksi;\r\nd. Pelaksanaan serah terima hasil pekerjaan;\r\ne. Konsesi dan kerjasama pengoperasian pelabuhan.', 2208000000, 0, 2016, 60, '1. Ketersediaan fasilitas terminal kontainer untuk mendukung pertumbuhan dan kegiatan\r\nkawasan industri khususnya di wilayah Jawa Barat bagian Tengah dan Utara;\r\n2. Ketersediaan fasilitas terminal kendaraan bermotor dalam rangka menunjang\r\npertumbuhan industri otomotif nasional;\r\n3. Ketersediaan fasilitas kapal Roro untuk penyeberangan antar pulau.', 'a. Menekan biaya logistik dengan mendekatkan pusat produksi (industri manufaktur) dengan outlet pelabuhan;\r\nb. Memperkuat ketahanan perekonomian dengan menyediakan backup outlet pelabuhan yang melayani wilayah industri yang menghasilkan +- 70% kargo dalam negeri;\r\nc. Menurunkan tingkat kemacetan dan mengurangi kerugian akibat kemacetan di Ibukota Negara dengan memindahkan sebagian trafik angkutan berat ke luar wilayah Ibukota;\r\nd. Menekan penggunaan BBM(bersubsidi) dan meningkatkan utilisasi truk kontainer dengan memperpendek jarak tempuh dari industri manufaktur ke pelabuhan;\r\ne. Menjamin keselamatan pelayaran dan area eksplorasi migas di kawasan lepas pantai Utara Jawa Barat;\r\nf. Membantu pertumbuhan dan perkembangan wilayah Kabupaten Subang dan Provinsi Jawa Barat secara umum.', 595000000, 1, 1, 1, 1, '', 'undefined', 6, 1, 1, 0, '26', '[object HTMLSelectElement]', '[object HTMLSelectElement]'),
	(38, '23', '', 'a. Direktorat Jenderal Sumber Daya Air\r\nb. BBWS Sumatera VIII', '5', 2015, 'Pekerjaan Irigasi Komering Tahap III', 'Komering Irrigation Project Stage III', 'Proyek yang diusulkan meliputi :\r\ni) review desain jaringan irigasi utama dan tersier Lempuing\r\nseluas 8.500 ha,\r\n ii) pekerjaan sipil untuk jaringan irigasi utama dan tersier Lempuing seluas 8.500\r\nha,\r\niii) pekerjaan sipil untuk perbaikan fasilitas irigasi yang sudah ada, \r\niv) soft komponen untuk memperkuat pengelolaan air irigasi di Lempuing,\r\n v) review rencana pembangunan secara keseluruhan Proyek Irigasi Komering', 'The proposed project includes :\r\n i) review of design of main and tertian; irrigation system in Lempuing\r\nscheme for 8,500 ha, \r\nii) civil works for main and tertiary irrigation system in Lempuing scheme for 8,500\r\nha, \r\niii) civil works for improvement of existing irrigation facilities, \r\niv) soft component for strengthening of irrigation water management in Lempuing scheme, \r\nv) review of overall development plan of Komering Irrigation Project', 120000000, 0, 2015, 96, '1. Pembangunan saluran sekunder dan saluran sub-sekunder Lempuing: 85 km\r\n2. Peningkatan Jaringan Tersier: 8.500 ha\r\n3. Peningkatan fasilitas irigasi yang sudah ada di Bendung Perjaya, saluran utama, dan saluran\r\nsekunder Belitang.\r\n4. Soft Component: penguatan pengelolaan air irigasi\r\n5. Review Rencana Pembangunan Keseluruhan Proyek Irigasi', '1. Peningkatan daerah irigasi 8.500 ha\r\n2. Meningkatkan itensitas penanaman padi dari yang saat ini 100% menjadi 250%\r\n3. Meningkatkan produksi padi dari yang saat ini 3,0 ton/ha menjadi 5,0 ton/ha', 12000000, 1, 1, 0, 0, '', '369', 3, 1, 1, 0, '0', NULL, NULL),
	(65, '23', '', 'a. Direktorat Jenderal Sumber Daya Air\r\nb. Balai Besar / Balai WS', '6', 2015, 'Penyiapan teknis untuk pembangunan waduk serbaguna', 'Engineering Service for Dam Multipurpose Development Project', 'a. Analisis rencana teknis pembangunan bendungan beserta fasilitasnya, operasi,\r\npemeliharaan dan mekanisme pengadaan barang dan jasa\r\nb. Analisis penyiapan detail desain, pengadaan lahan dan rencana pemukiman kembali\r\nserta AMDAL\r\nc. Melaksanakan perencanaan program, analisis pembiayaan proyek dan persiapan\r\ndokumen lelang', 'a. Conducting analysis in term of operaion, maintenance, facilty construction and procurement plans\r\nb. Conducting analysis in term of detailed design, land acquistion, resstlement plan and environmental impact assessment\r\nc. Implementing the program planning, project funding analysis and tender document preparation', 100000000, 0, 2015, 60, 'a. Detail desain pembangunan bendungan dan kelengkapan dokumen AMDAL,LARAP\r\nb. Mekanisme pengadaaan, rencana pelaksanaan dan standar dokumen pengadaan\r\nc. Manajemen pengelolaan proyek dan analisis pembiayaannya', 'a. Meningkatkan perencanaan untuk persiapan pembangunan bendungan beserta fasilitas\r\npendukungnya dan mekanisme pengadaan barang!jasanya\r\nb. Analisa biaya dan manfaat (B/C ratio) dari sebelum dan sesudah ada proyek', 0, 1, 1, 0, 0, '', 'undefined', 3, 1, 1, 0, '26', '[object HTMLSelectElement]', '[object HTMLSelectElement]'),
	(103, '23', '', 'a. Direktorat Jenderal Sumber Daya Air\r\nb. BBWS Cidanau Ciujung Cidurian\r\nc. BBWS Mesuji Sekampung', '5', 2015, 'Rehabilitasi Mendesak untuk Irigasi yang Strategis di Indonesia Bagian Barat', 'The Urgent Rehabilitation of Strategic Irrigation for Western Region of Indonesia', 'a. Rehabilitasi dan modernisasi fasilitas irigasi\r\nb. Meningkatkan sistem irigasi dan drainase (baru)\r\nc. Peningkatan kapasitas O&P', 'a. Rehabilitation and modernization of irrigation facilities\r\nb. Improvement of irrgation and drainage systems (new)\r\nc. O&M capacity building', 195777777, 0, 2015, 48, 'a. Untuk menjamin semua kegiatan pertanian dengan merehabilitasi dan memodernisasi sistem irigasi dan drainase yang rusak dan memburuk;\r\nb. Untuk meningkatkan produksi pertanian dan berkontribusi terhadap swasembada pangan;\r\nc. Untuk meningkatkan pendapatan petani dengan penggunaan lahan instensif di daerah subur, dan mengembangkan praktek-praktek budidaya baru;\r\nd. Untuk meningkatkan kesempatan kerja, khususnya bagi penduduk pedesaan;\r\ne. Untuk meningkatkan kondisi kehidupan penduduk di wilayah Proyek dan menyediakan pasokan air desa yang tepat;\r\nf. Untuk meningkatkan penerapan O&P dan\r\ng. Untuk memperkuat WUA dan FWUA (Federasi APA) untuk mengadopsi PIM (Pengelolaan Irigasi Partisipatif)', 'a. Rehabilitasi Mendesak untuk Irigasi yang Strategis di Indonesia Bagian Barat seluas 38,523 Ha (Teluk Lada 19,618 ha, Rawa Sragi 1 dan Rawa Pisang 19,118 ha)', 27149523, 1, 0, 0, 0, '', '341,356', 3, 1, 1, 0, '0', NULL, NULL),
	(104, '23', '', 'a. Direktorat Jenderal Pembiayaan Perumahan;\r\nb. Kementerian Keuangan;\r\nc. Otoritas Jasa Keuangan (OJK);\r\nd. Lembaga Pembiayaan', '13', 2017, 'Program Dukungan Pembiayaan Perumahan Bagi Rumah Tangga Berpenghasilan Rendah', 'Financial Support for Low Income Households', 'a. Capacity Building of Financial Institutions\r\nb. Housing Micro Finance System', 'a. Capacity Building of Financial Institutions\r\nb. Housing Micro Finance System', 300000000, 7000000, 2016, 36, 'a. Capacity Building Report on Financing Institutions in selected cities;\r\nb. Operational standards implementation in Mortgage Financing Institutions (mortgage center);\r\nc. Documentation of Good Practices on Housing Micro Finance Initiatives;\r\nd. Market profile for Housing Finance in selected cities;\r\ne. Training Implementation Report for Financial Institutions and MFIs in selected cities;\r\nf. A Concept Note of Housing Micro Finance Product;\r\ng. Report study of the housing market in Indonesia.', 'a. Capacity Financial Institutions Assesment\r\nb. Market Demand Assesment\r\nc. Market Study Housing in Indonesia\r\nd. Pilotting', 30000000, 1, 0, 0, 0, '', '344', 10, 1, 1, 0, '0', NULL, NULL),
	(105, '23', '', 'a. Direktorat Jenderal Pembiayaan Perumahan;\r\nb. Direktorat Jenderal Penyediaan Perumahan.', '13', 2017, 'National Affordable Housing Program', 'National Affordable Housing Program', '1. Savings-Subsidy Housing Finance\r\n2. Perumahan Swadaya\r\n3. Technical Assistance for Strengthening Housing Sector Management', '1. Savings-Subsidy Housing Finance\r\n2. Perumahan Swadaya\r\n3. Technical Assistance for Strengthening Housing Sector Management', 450000000, 0, 2016, 36, '1. Savings-Subsidy Housing Finance\r\n2. Perumahan Swadaya\r\n3. Technical Assistance for Strengthening Housing Sector Management', '1. Savings-Subsidy Housing Finance\r\n2. Perumahan Swadaya\r\n3. Technical Assistance for Strengthening Housing Sector Management', 0, 1, 1, 1, 1, '', '344', 10, 1, 1, 1, '104', NULL, NULL),
	(106, '23', '', 'Direktorat Jenderal Bina Marga Kementerian PUPR', '10', 2016, 'Pembangunan Jalan Tol Balikpapan - Samarinda', 'Toll Road Development of Balikpapan - Samarinda', '-', '-', 65000000, 0, 2015, 36, '-', '-', 0, 0, 0, 0, 0, '', 'undefined', 4, 1, 1, 0, '0', 'null', 'null'),
	(107, '23', '', 'Direktorat Jenderal Bina Marga Kementerian PUPR', '10', 2016, 'Pembangunan Jalan Tol Solo - Kertosono', 'Toll Road Development of Solo - Kertosono', '-', '-', 200000000, 0, 2015, 36, 'Konstruksi jalan tol Solo-Kertsono sepanjang 26,45 KM', 'a. Perbaikan akses dan peningkatan kapasitas jaringan jalan serta distribusi barang dalam ruas Jogja - Surabaya dan kota disekitarnya yang sejalan dengna pertumbuhan perekonomian dan wilayah.', 0, 0, 0, 0, 0, '', 'undefined', 4, 1, 1, 0, '0', '10', 'null'),
	(108, '23', '', 'Direktorat Jenderal Bina Marga Kementerian PUPR', '10', 2016, 'Pembangunan Jalan Tol  Manado - Bitung', 'Toll Road Development of Manado - Bitung', '-', '-', 80000000, 0, 2015, 36, '-', '-', 0, 0, 0, 0, 0, '', 'undefined', 4, 1, 1, 0, '0', '31', 'null'),
	(109, '23', '', 'Direktorat Jenderal Cipta Karya, Kementerian PUPR', '4', 2016, 'Program Peningkatan Kualitas Pemukiman Kumuh', 'National Slum Upgrading', '-', '-', 722880000, 0, 2015, 60, '-', '-', 0, 0, 0, 0, 0, '', 'undefined', 1, 1, 1, 0, '0', '6', 'null'),
	(110, '23', '', 'Kementerian PUPR', '17', 2016, 'Penyiapan teknis untuk proyek pembangunan jaringan irigasi dan rawa', 'Engineering Service for Irrigation and Lowland Development Project', '-', '-', 100000000, 0, 2015, 60, '-', '-', 0, 0, 0, 0, 0, '', 'undefined', 3, 1, 1, 0, '26', '[object HTMLSelectElement]', '[object HTMLSelectElement]'),
	(111, '23', '', 'a. Direktorat Jenderal Sumber Daya Air\r\nb. Balai Besar / Balai Wilayah Sungai', '6', 2016, 'Penyiapan Teknik Sistem Penyediaan Air Baku', 'Engineering Service for Bulk Water and Water Supply Development Project', '-', '-', 50000000, 0, 2015, 60, '-', '-', 0, 0, 0, 0, 0, '', 'undefined', 3, 1, 1, 0, '0', '6', 'null'),
	(112, '23', '', 'Ditjen Sumber Daya Air, Kementerian PUPR', '3', 2015, 'Kegiatan Sektor Manajemen Pengelolaan Banjir di Wilayah Sungai Terpilih', 'Flood management in Selected River Basins Sector Project', '-', '-', 108700000, 0, 2015, 72, '-', '-', 50440000, 0, 0, 0, 0, '', 'undefined', 3, 1, 1, 0, '0', '6', 'null'),
	(113, '23', '', 'a. Direktorat Jenderal Cipta Karya', '3', 2010, 'Penyediaan IPA skala kecil (IPA mobile) untuk penanganan darurat', 'Small Scale Water Treatment Plant for Emergency Relief', '-', '-', 25000000, 0, 2010, 24, '-', '-', 800000, 0, 0, 0, 0, '', 'undefined', 14, 1, 1, 0, '0', '6', 'null'),
	(114, '23', '', 'a. Direktorat Jenderal Sumber Daya Air\r\nb. BBWS Cimanusk Cisanggarung', '5', 2016, 'Proyek Modernisasi Irigasi Rentang', 'Rentang Irrigation Modernization Project (RIMP)', '-', '-', 480000000, 0, 2015, 97, '-', '-', 48000000, 0, 0, 0, 0, '', 'undefined', 3, 1, 1, 0, '0', '9', '75'),
	(115, '23', '', 'Kementerian PUPR', '1', 2015, 'Pekerjaan Irigasi Komering Tahap III', 'Komering Irrigation Project Stage III', '-', '-', 120000000, 0, 2015, 96, '-', '-', 12000000, 0, 0, 0, 0, '', 'undefined', 1, 1, 1, 0, '0', '33', 'null'),
	(116, '23', '', 'a. Direktorat Jenderal Sumber Daya Air\r\nb. BWS Bali Penida', '17', 2015, 'Proyek Pengamanan Pantai Bali Tahap - 2', 'Bali Beach Conservation Project Phase II', '-', '-', 150000000, 0, 2015, 65, '-', '-', 15000000, 0, 0, 0, 0, '', 'undefined', 3, 1, 1, 0, '0', '1', 'null'),
	(117, '23', '', 'Kementerian PUPR', '18', 2017, 'Penyusunan Rencana Induk Terpadu Pembangunan Destinasi Pariwisata Prioritas', 'Integrated Masterplan for Priority Tourism Destination', '-', '-', 4000000, 2000000, 2015, 12, '-', '-', 0, 0, 0, 0, 0, '', 'undefined', 12, 1, 1, 0, '0', '10,22,34', 'null'),
	(118, '23', '', 'Direktorat Jenderal Bina Marga Kementerian PUPR', '8', 2016, 'Pembangunan Konstruksi Jalan Trans Selatan Selatan Pulau Jawa', 'Construction Development of Trans South South Java Island', '-', '-', 250000000, 0, 2015, 48, '-', '-', 50000000, 0, 0, 0, 0, '', 'undefined', 4, 1, 1, 0, '0', '3,5,9,10,11', 'null'),
	(119, '90', '', 'PT. PLN', '2', 2011, 'Construction of Java - Sumatera 500kV Line (HVDC) Interconnection', 'Konstruksi Transmisi 500kV (HVDC) Interkoneksi Jawa - Sumatera Phase I', '-', '-', 938000000, 0, 2015, 42, '-', '-', 48000000, 0, 0, 0, 0, '', 'undefined', 14, 1, 1, 0, '0', '33', 'null');
/*!40000 ALTER TABLE `irena_usulan_pln` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
